Traceback (most recent call last):
  File "c:\30\Traceback.py", line 11, in <module>
    CheckSpeed(speed)
    ~~~~~~~~~~^^^^^^^
  File "c:\30\Traceback.py", line 5, in CheckSpeed
    raise Exception("³t«×¤ÓºC¤F")
Exception: ³t«×¤ÓºC¤F
Traceback (most recent call last):
  File "c:\30\Traceback.py", line 11, in <module>
    CheckSpeed(speed)
    ~~~~~~~~~~^^^^^^^
  File "c:\30\Traceback.py", line 7, in CheckSpeed
    raise Exception("³t«×¤Ó§Ö¤F")
Exception: ³t«×¤Ó§Ö¤F
Traceback (most recent call last):
  File "c:\30\Traceback.py", line 11, in <module>
    CheckSpeed(speed)
    ~~~~~~~~~~^^^^^^^
  File "c:\30\Traceback.py", line 5, in CheckSpeed
    raise Exception("é€Ÿåº¦å¤ªæ…¢äº†")
Exception: é€Ÿåº¦å¤ªæ…¢äº†
Traceback (most recent call last):
  File "c:\30\Traceback.py", line 11, in <module>
    CheckSpeed(speed)
    ~~~~~~~~~~^^^^^^^
  File "c:\30\Traceback.py", line 7, in CheckSpeed
    raise Exception("é€Ÿåº¦å¤ªå¿«äº†")
Exception: é€Ÿåº¦å¤ªå¿«äº†
